# Generated by Django 6.0.5 on 2026-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_candidateprofile_recruiterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
