# Generated by Django 6.0.5 on 2026-07-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_candidateprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='premium_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='premium_plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='premium_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
