# Generated by Django 6.0.6 on 2026-07-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_blocked',
        ),
    ]
