# Generated by Django 6.0.5 on 2026-07-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_candidateprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('requirements', models.TextField()),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time')], max_length=20)),
                ('experience', models.CharField(choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'available'), ('closed', 'closed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.category')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.recruiterprofile')),
            ],
        ),
    ]
