# Generated by Django 6.0.6 on 2026-07-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-solid fa-briefcase', max_length=100),
        ),
    ]
